/* tslint:disable */
/* eslint-disable */
/**
 * Specialist Booking API
 * Specialist appointment booking management for Web-In-Cloud system
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: xdrga@stuba.sk
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Appointment
 */
export interface Appointment {
    /**
     * Unique id of appointment
     * @type {string}
     * @memberof Appointment
     */
    id: string;
    /**
     * Unique identifier of the patient known to Web-In-Cloud system
     * @type {string}
     * @memberof Appointment
     */
    patientId: string;
    /**
     * Name of patient for this appointment
     * @type {string}
     * @memberof Appointment
     */
    patientName: string;
    /**
     * Scheduled start timestamp
     * @type {Date}
     * @memberof Appointment
     */
    startsAt: Date;
    /**
     * Duration of appointment in minutes
     * @type {number}
     * @memberof Appointment
     */
    durationMinutes: number;
    /**
     * Requested examination type
     * @type {string}
     * @memberof Appointment
     */
    examinationType: string;
    /**
     * Workflow state of appointment
     * @type {string}
     * @memberof Appointment
     */
    status: string;
    /**
     * Optional note
     * @type {string}
     * @memberof Appointment
     */
    note?: string;
}

/**
 * Check if a given object implements the Appointment interface.
 */
export function instanceOfAppointment(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "id" in value;
    isInstance = isInstance && "patientId" in value;
    isInstance = isInstance && "patientName" in value;
    isInstance = isInstance && "startsAt" in value;
    isInstance = isInstance && "durationMinutes" in value;
    isInstance = isInstance && "examinationType" in value;
    isInstance = isInstance && "status" in value;

    return isInstance;
}

export function AppointmentFromJSON(json: any): Appointment {
    return AppointmentFromJSONTyped(json, false);
}

export function AppointmentFromJSONTyped(json: any, ignoreDiscriminator: boolean): Appointment {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'patientId': json['patientId'],
        'patientName': json['patientName'],
        'startsAt': (new Date(json['startsAt'])),
        'durationMinutes': json['durationMinutes'],
        'examinationType': json['examinationType'],
        'status': json['status'],
        'note': !exists(json, 'note') ? undefined : json['note'],
    };
}

export function AppointmentToJSON(value?: Appointment | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'patientId': value.patientId,
        'patientName': value.patientName,
        'startsAt': (value.startsAt.toISOString()),
        'durationMinutes': value.durationMinutes,
        'examinationType': value.examinationType,
        'status': value.status,
        'note': value.note,
    };
}

