/* tslint:disable */
/* eslint-disable */
/**
 * Specialist Booking API
 * Specialist appointment booking management for Web-In-Cloud system
 *
 * The version of the OpenAPI document: 1.1.0
 * Contact: xdrga@stuba.sk
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Appointment
 */
export interface Appointment {
    /**
     * 
     * @type {string}
     * @memberof Appointment
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof Appointment
     */
    patientId: string;
    /**
     * 
     * @type {string}
     * @memberof Appointment
     */
    patientName: string;
    /**
     * 
     * @type {string}
     * @memberof Appointment
     */
    patientEmail?: string;
    /**
     * 
     * @type {string}
     * @memberof Appointment
     */
    referringDoctor?: string;
    /**
     * 
     * @type {Date}
     * @memberof Appointment
     */
    startsAt: Date;
    /**
     * 
     * @type {number}
     * @memberof Appointment
     */
    durationMinutes: number;
    /**
     * 
     * @type {string}
     * @memberof Appointment
     */
    examinationType: string;
    /**
     * 
     * @type {string}
     * @memberof Appointment
     */
    status: AppointmentStatusEnum;
    /**
     * 
     * @type {string}
     * @memberof Appointment
     */
    assignedSlotId?: string;
    /**
     * 
     * @type {string}
     * @memberof Appointment
     */
    note?: string;
}


/**
 * @export
 */
export const AppointmentStatusEnum = {
    Requested: 'requested',
    Confirmed: 'confirmed',
    Completed: 'completed',
    Cancelled: 'cancelled'
} as const;
export type AppointmentStatusEnum = typeof AppointmentStatusEnum[keyof typeof AppointmentStatusEnum];


/**
 * Check if a given object implements the Appointment interface.
 */
export function instanceOfAppointment(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "id" in value;
    isInstance = isInstance && "patientId" in value;
    isInstance = isInstance && "patientName" in value;
    isInstance = isInstance && "startsAt" in value;
    isInstance = isInstance && "durationMinutes" in value;
    isInstance = isInstance && "examinationType" in value;
    isInstance = isInstance && "status" in value;

    return isInstance;
}

export function AppointmentFromJSON(json: any): Appointment {
    return AppointmentFromJSONTyped(json, false);
}

export function AppointmentFromJSONTyped(json: any, ignoreDiscriminator: boolean): Appointment {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'patientId': json['patientId'],
        'patientName': json['patientName'],
        'patientEmail': !exists(json, 'patientEmail') ? undefined : json['patientEmail'],
        'referringDoctor': !exists(json, 'referringDoctor') ? undefined : json['referringDoctor'],
        'startsAt': (new Date(json['startsAt'])),
        'durationMinutes': json['durationMinutes'],
        'examinationType': json['examinationType'],
        'status': json['status'],
        'assignedSlotId': !exists(json, 'assignedSlotId') ? undefined : json['assignedSlotId'],
        'note': !exists(json, 'note') ? undefined : json['note'],
    };
}

export function AppointmentToJSON(value?: Appointment | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'patientId': value.patientId,
        'patientName': value.patientName,
        'patientEmail': value.patientEmail,
        'referringDoctor': value.referringDoctor,
        'startsAt': (value.startsAt.toISOString()),
        'durationMinutes': value.durationMinutes,
        'examinationType': value.examinationType,
        'status': value.status,
        'assignedSlotId': value.assignedSlotId,
        'note': value.note,
    };
}

