/* tslint:disable */
/* eslint-disable */
/**
 * Specialist Booking API
 * Specialist appointment booking management for Web-In-Cloud system
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: xdrga@stuba.sk
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TimeSlot
 */
export interface TimeSlot {
    /**
     * 
     * @type {string}
     * @memberof TimeSlot
     */
    id: string;
    /**
     * 
     * @type {Date}
     * @memberof TimeSlot
     */
    startsAt: Date;
    /**
     * 
     * @type {number}
     * @memberof TimeSlot
     */
    durationMinutes: number;
    /**
     * 
     * @type {number}
     * @memberof TimeSlot
     */
    capacity: number;
    /**
     * 
     * @type {number}
     * @memberof TimeSlot
     */
    booked: number;
    /**
     * 
     * @type {string}
     * @memberof TimeSlot
     */
    examinationType: string;
    /**
     * 
     * @type {boolean}
     * @memberof TimeSlot
     */
    urgentBlocked: boolean;
}

/**
 * Check if a given object implements the TimeSlot interface.
 */
export function instanceOfTimeSlot(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "id" in value;
    isInstance = isInstance && "startsAt" in value;
    isInstance = isInstance && "durationMinutes" in value;
    isInstance = isInstance && "capacity" in value;
    isInstance = isInstance && "booked" in value;
    isInstance = isInstance && "examinationType" in value;
    isInstance = isInstance && "urgentBlocked" in value;

    return isInstance;
}

export function TimeSlotFromJSON(json: any): TimeSlot {
    return TimeSlotFromJSONTyped(json, false);
}

export function TimeSlotFromJSONTyped(json: any, ignoreDiscriminator: boolean): TimeSlot {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'startsAt': (new Date(json['startsAt'])),
        'durationMinutes': json['durationMinutes'],
        'capacity': json['capacity'],
        'booked': json['booked'],
        'examinationType': json['examinationType'],
        'urgentBlocked': json['urgentBlocked'],
    };
}

export function TimeSlotToJSON(value?: TimeSlot | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'startsAt': (value.startsAt.toISOString()),
        'durationMinutes': value.durationMinutes,
        'capacity': value.capacity,
        'booked': value.booked,
        'examinationType': value.examinationType,
        'urgentBlocked': value.urgentBlocked,
    };
}

