/* tslint:disable */
/* eslint-disable */
/**
 * Specialist Booking API
 * Specialist appointment booking management for Web-In-Cloud system
 *
 * The version of the OpenAPI document: 1.1.0
 * Contact: xdrga@stuba.sk
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  Appointment,
  AssignBestSlotResponse,
  ErrorResponse,
  TimeSlot,
  WaitingListEntry,
} from '../models';
import {
    AppointmentFromJSON,
    AppointmentToJSON,
    AssignBestSlotResponseFromJSON,
    AssignBestSlotResponseToJSON,
    ErrorResponseFromJSON,
    ErrorResponseToJSON,
    TimeSlotFromJSON,
    TimeSlotToJSON,
    WaitingListEntryFromJSON,
    WaitingListEntryToJSON,
} from '../models';

export interface AssignBestSlotRequest {
    clinicId: string;
    appointmentId: string;
}

export interface CreateAppointmentRequest {
    clinicId: string;
    appointment: Appointment;
}

export interface CreateTimeSlotRequest {
    clinicId: string;
    timeSlot: TimeSlot;
}

export interface DeleteAppointmentRequest {
    clinicId: string;
    appointmentId: string;
}

export interface DeleteTimeSlotRequest {
    clinicId: string;
    slotId: string;
}

export interface GetAppointmentRequest {
    clinicId: string;
    appointmentId: string;
}

export interface GetAppointmentsRequest {
    clinicId: string;
}

export interface GetTimeSlotRequest {
    clinicId: string;
    slotId: string;
}

export interface GetTimeSlotsRequest {
    clinicId: string;
}

export interface GetWaitingListRequest {
    clinicId: string;
}

export interface UpdateAppointmentRequest {
    clinicId: string;
    appointmentId: string;
    appointment: Appointment;
}

export interface UpdateTimeSlotRequest {
    clinicId: string;
    slotId: string;
    timeSlot: TimeSlot;
}

/**
 * SpecialistBookingApi - interface
 * 
 * @export
 * @interface SpecialistBookingApiInterface
 */
export interface SpecialistBookingApiInterface {
    /**
     * 
     * @param {string} clinicId 
     * @param {string} appointmentId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SpecialistBookingApiInterface
     */
    assignBestSlotRaw(requestParameters: AssignBestSlotRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AssignBestSlotResponse>>;

    /**
     */
    assignBestSlot(requestParameters: AssignBestSlotRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AssignBestSlotResponse>;

    /**
     * 
     * @param {string} clinicId 
     * @param {Appointment} appointment 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SpecialistBookingApiInterface
     */
    createAppointmentRaw(requestParameters: CreateAppointmentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Appointment>>;

    /**
     */
    createAppointment(requestParameters: CreateAppointmentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Appointment>;

    /**
     * 
     * @param {string} clinicId 
     * @param {TimeSlot} timeSlot 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SpecialistBookingApiInterface
     */
    createTimeSlotRaw(requestParameters: CreateTimeSlotRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TimeSlot>>;

    /**
     */
    createTimeSlot(requestParameters: CreateTimeSlotRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TimeSlot>;

    /**
     * 
     * @param {string} clinicId 
     * @param {string} appointmentId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SpecialistBookingApiInterface
     */
    deleteAppointmentRaw(requestParameters: DeleteAppointmentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>>;

    /**
     */
    deleteAppointment(requestParameters: DeleteAppointmentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void>;

    /**
     * 
     * @param {string} clinicId 
     * @param {string} slotId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SpecialistBookingApiInterface
     */
    deleteTimeSlotRaw(requestParameters: DeleteTimeSlotRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>>;

    /**
     */
    deleteTimeSlot(requestParameters: DeleteTimeSlotRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void>;

    /**
     * 
     * @param {string} clinicId 
     * @param {string} appointmentId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SpecialistBookingApiInterface
     */
    getAppointmentRaw(requestParameters: GetAppointmentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Appointment>>;

    /**
     */
    getAppointment(requestParameters: GetAppointmentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Appointment>;

    /**
     * 
     * @param {string} clinicId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SpecialistBookingApiInterface
     */
    getAppointmentsRaw(requestParameters: GetAppointmentsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<Appointment>>>;

    /**
     */
    getAppointments(requestParameters: GetAppointmentsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<Appointment>>;

    /**
     * 
     * @param {string} clinicId 
     * @param {string} slotId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SpecialistBookingApiInterface
     */
    getTimeSlotRaw(requestParameters: GetTimeSlotRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TimeSlot>>;

    /**
     */
    getTimeSlot(requestParameters: GetTimeSlotRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TimeSlot>;

    /**
     * 
     * @param {string} clinicId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SpecialistBookingApiInterface
     */
    getTimeSlotsRaw(requestParameters: GetTimeSlotsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<TimeSlot>>>;

    /**
     */
    getTimeSlots(requestParameters: GetTimeSlotsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<TimeSlot>>;

    /**
     * 
     * @param {string} clinicId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SpecialistBookingApiInterface
     */
    getWaitingListRaw(requestParameters: GetWaitingListRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<WaitingListEntry>>>;

    /**
     */
    getWaitingList(requestParameters: GetWaitingListRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<WaitingListEntry>>;

    /**
     * 
     * @param {string} clinicId 
     * @param {string} appointmentId 
     * @param {Appointment} appointment 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SpecialistBookingApiInterface
     */
    updateAppointmentRaw(requestParameters: UpdateAppointmentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Appointment>>;

    /**
     */
    updateAppointment(requestParameters: UpdateAppointmentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Appointment>;

    /**
     * 
     * @param {string} clinicId 
     * @param {string} slotId 
     * @param {TimeSlot} timeSlot 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SpecialistBookingApiInterface
     */
    updateTimeSlotRaw(requestParameters: UpdateTimeSlotRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TimeSlot>>;

    /**
     */
    updateTimeSlot(requestParameters: UpdateTimeSlotRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TimeSlot>;

}

/**
 * 
 */
export class SpecialistBookingApi extends runtime.BaseAPI implements SpecialistBookingApiInterface {

    /**
     */
    async assignBestSlotRaw(requestParameters: AssignBestSlotRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AssignBestSlotResponse>> {
        if (requestParameters.clinicId === null || requestParameters.clinicId === undefined) {
            throw new runtime.RequiredError('clinicId','Required parameter requestParameters.clinicId was null or undefined when calling assignBestSlot.');
        }

        if (requestParameters.appointmentId === null || requestParameters.appointmentId === undefined) {
            throw new runtime.RequiredError('appointmentId','Required parameter requestParameters.appointmentId was null or undefined when calling assignBestSlot.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/specialist-booking/{clinicId}/appointments/{appointmentId}/assign-best-slot`.replace(`{${"clinicId"}}`, encodeURIComponent(String(requestParameters.clinicId))).replace(`{${"appointmentId"}}`, encodeURIComponent(String(requestParameters.appointmentId))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AssignBestSlotResponseFromJSON(jsonValue));
    }

    /**
     */
    async assignBestSlot(requestParameters: AssignBestSlotRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AssignBestSlotResponse> {
        const response = await this.assignBestSlotRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async createAppointmentRaw(requestParameters: CreateAppointmentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Appointment>> {
        if (requestParameters.clinicId === null || requestParameters.clinicId === undefined) {
            throw new runtime.RequiredError('clinicId','Required parameter requestParameters.clinicId was null or undefined when calling createAppointment.');
        }

        if (requestParameters.appointment === null || requestParameters.appointment === undefined) {
            throw new runtime.RequiredError('appointment','Required parameter requestParameters.appointment was null or undefined when calling createAppointment.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/specialist-booking/{clinicId}/appointments`.replace(`{${"clinicId"}}`, encodeURIComponent(String(requestParameters.clinicId))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: AppointmentToJSON(requestParameters.appointment),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AppointmentFromJSON(jsonValue));
    }

    /**
     */
    async createAppointment(requestParameters: CreateAppointmentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Appointment> {
        const response = await this.createAppointmentRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async createTimeSlotRaw(requestParameters: CreateTimeSlotRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TimeSlot>> {
        if (requestParameters.clinicId === null || requestParameters.clinicId === undefined) {
            throw new runtime.RequiredError('clinicId','Required parameter requestParameters.clinicId was null or undefined when calling createTimeSlot.');
        }

        if (requestParameters.timeSlot === null || requestParameters.timeSlot === undefined) {
            throw new runtime.RequiredError('timeSlot','Required parameter requestParameters.timeSlot was null or undefined when calling createTimeSlot.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/specialist-booking/{clinicId}/time-slots`.replace(`{${"clinicId"}}`, encodeURIComponent(String(requestParameters.clinicId))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: TimeSlotToJSON(requestParameters.timeSlot),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TimeSlotFromJSON(jsonValue));
    }

    /**
     */
    async createTimeSlot(requestParameters: CreateTimeSlotRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TimeSlot> {
        const response = await this.createTimeSlotRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async deleteAppointmentRaw(requestParameters: DeleteAppointmentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters.clinicId === null || requestParameters.clinicId === undefined) {
            throw new runtime.RequiredError('clinicId','Required parameter requestParameters.clinicId was null or undefined when calling deleteAppointment.');
        }

        if (requestParameters.appointmentId === null || requestParameters.appointmentId === undefined) {
            throw new runtime.RequiredError('appointmentId','Required parameter requestParameters.appointmentId was null or undefined when calling deleteAppointment.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/specialist-booking/{clinicId}/appointments/{appointmentId}`.replace(`{${"clinicId"}}`, encodeURIComponent(String(requestParameters.clinicId))).replace(`{${"appointmentId"}}`, encodeURIComponent(String(requestParameters.appointmentId))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async deleteAppointment(requestParameters: DeleteAppointmentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.deleteAppointmentRaw(requestParameters, initOverrides);
    }

    /**
     */
    async deleteTimeSlotRaw(requestParameters: DeleteTimeSlotRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters.clinicId === null || requestParameters.clinicId === undefined) {
            throw new runtime.RequiredError('clinicId','Required parameter requestParameters.clinicId was null or undefined when calling deleteTimeSlot.');
        }

        if (requestParameters.slotId === null || requestParameters.slotId === undefined) {
            throw new runtime.RequiredError('slotId','Required parameter requestParameters.slotId was null or undefined when calling deleteTimeSlot.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/specialist-booking/{clinicId}/time-slots/{slotId}`.replace(`{${"clinicId"}}`, encodeURIComponent(String(requestParameters.clinicId))).replace(`{${"slotId"}}`, encodeURIComponent(String(requestParameters.slotId))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async deleteTimeSlot(requestParameters: DeleteTimeSlotRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.deleteTimeSlotRaw(requestParameters, initOverrides);
    }

    /**
     */
    async getAppointmentRaw(requestParameters: GetAppointmentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Appointment>> {
        if (requestParameters.clinicId === null || requestParameters.clinicId === undefined) {
            throw new runtime.RequiredError('clinicId','Required parameter requestParameters.clinicId was null or undefined when calling getAppointment.');
        }

        if (requestParameters.appointmentId === null || requestParameters.appointmentId === undefined) {
            throw new runtime.RequiredError('appointmentId','Required parameter requestParameters.appointmentId was null or undefined when calling getAppointment.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/specialist-booking/{clinicId}/appointments/{appointmentId}`.replace(`{${"clinicId"}}`, encodeURIComponent(String(requestParameters.clinicId))).replace(`{${"appointmentId"}}`, encodeURIComponent(String(requestParameters.appointmentId))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AppointmentFromJSON(jsonValue));
    }

    /**
     */
    async getAppointment(requestParameters: GetAppointmentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Appointment> {
        const response = await this.getAppointmentRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async getAppointmentsRaw(requestParameters: GetAppointmentsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<Appointment>>> {
        if (requestParameters.clinicId === null || requestParameters.clinicId === undefined) {
            throw new runtime.RequiredError('clinicId','Required parameter requestParameters.clinicId was null or undefined when calling getAppointments.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/specialist-booking/{clinicId}/appointments`.replace(`{${"clinicId"}}`, encodeURIComponent(String(requestParameters.clinicId))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(AppointmentFromJSON));
    }

    /**
     */
    async getAppointments(requestParameters: GetAppointmentsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<Appointment>> {
        const response = await this.getAppointmentsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async getTimeSlotRaw(requestParameters: GetTimeSlotRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TimeSlot>> {
        if (requestParameters.clinicId === null || requestParameters.clinicId === undefined) {
            throw new runtime.RequiredError('clinicId','Required parameter requestParameters.clinicId was null or undefined when calling getTimeSlot.');
        }

        if (requestParameters.slotId === null || requestParameters.slotId === undefined) {
            throw new runtime.RequiredError('slotId','Required parameter requestParameters.slotId was null or undefined when calling getTimeSlot.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/specialist-booking/{clinicId}/time-slots/{slotId}`.replace(`{${"clinicId"}}`, encodeURIComponent(String(requestParameters.clinicId))).replace(`{${"slotId"}}`, encodeURIComponent(String(requestParameters.slotId))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TimeSlotFromJSON(jsonValue));
    }

    /**
     */
    async getTimeSlot(requestParameters: GetTimeSlotRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TimeSlot> {
        const response = await this.getTimeSlotRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async getTimeSlotsRaw(requestParameters: GetTimeSlotsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<TimeSlot>>> {
        if (requestParameters.clinicId === null || requestParameters.clinicId === undefined) {
            throw new runtime.RequiredError('clinicId','Required parameter requestParameters.clinicId was null or undefined when calling getTimeSlots.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/specialist-booking/{clinicId}/time-slots`.replace(`{${"clinicId"}}`, encodeURIComponent(String(requestParameters.clinicId))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(TimeSlotFromJSON));
    }

    /**
     */
    async getTimeSlots(requestParameters: GetTimeSlotsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<TimeSlot>> {
        const response = await this.getTimeSlotsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async getWaitingListRaw(requestParameters: GetWaitingListRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<WaitingListEntry>>> {
        if (requestParameters.clinicId === null || requestParameters.clinicId === undefined) {
            throw new runtime.RequiredError('clinicId','Required parameter requestParameters.clinicId was null or undefined when calling getWaitingList.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/specialist-booking/{clinicId}/waiting-list`.replace(`{${"clinicId"}}`, encodeURIComponent(String(requestParameters.clinicId))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(WaitingListEntryFromJSON));
    }

    /**
     */
    async getWaitingList(requestParameters: GetWaitingListRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<WaitingListEntry>> {
        const response = await this.getWaitingListRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async updateAppointmentRaw(requestParameters: UpdateAppointmentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Appointment>> {
        if (requestParameters.clinicId === null || requestParameters.clinicId === undefined) {
            throw new runtime.RequiredError('clinicId','Required parameter requestParameters.clinicId was null or undefined when calling updateAppointment.');
        }

        if (requestParameters.appointmentId === null || requestParameters.appointmentId === undefined) {
            throw new runtime.RequiredError('appointmentId','Required parameter requestParameters.appointmentId was null or undefined when calling updateAppointment.');
        }

        if (requestParameters.appointment === null || requestParameters.appointment === undefined) {
            throw new runtime.RequiredError('appointment','Required parameter requestParameters.appointment was null or undefined when calling updateAppointment.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/specialist-booking/{clinicId}/appointments/{appointmentId}`.replace(`{${"clinicId"}}`, encodeURIComponent(String(requestParameters.clinicId))).replace(`{${"appointmentId"}}`, encodeURIComponent(String(requestParameters.appointmentId))),
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: AppointmentToJSON(requestParameters.appointment),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AppointmentFromJSON(jsonValue));
    }

    /**
     */
    async updateAppointment(requestParameters: UpdateAppointmentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Appointment> {
        const response = await this.updateAppointmentRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async updateTimeSlotRaw(requestParameters: UpdateTimeSlotRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TimeSlot>> {
        if (requestParameters.clinicId === null || requestParameters.clinicId === undefined) {
            throw new runtime.RequiredError('clinicId','Required parameter requestParameters.clinicId was null or undefined when calling updateTimeSlot.');
        }

        if (requestParameters.slotId === null || requestParameters.slotId === undefined) {
            throw new runtime.RequiredError('slotId','Required parameter requestParameters.slotId was null or undefined when calling updateTimeSlot.');
        }

        if (requestParameters.timeSlot === null || requestParameters.timeSlot === undefined) {
            throw new runtime.RequiredError('timeSlot','Required parameter requestParameters.timeSlot was null or undefined when calling updateTimeSlot.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/specialist-booking/{clinicId}/time-slots/{slotId}`.replace(`{${"clinicId"}}`, encodeURIComponent(String(requestParameters.clinicId))).replace(`{${"slotId"}}`, encodeURIComponent(String(requestParameters.slotId))),
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: TimeSlotToJSON(requestParameters.timeSlot),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TimeSlotFromJSON(jsonValue));
    }

    /**
     */
    async updateTimeSlot(requestParameters: UpdateTimeSlotRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TimeSlot> {
        const response = await this.updateTimeSlotRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
