/* tslint:disable */
/* eslint-disable */
/**
 * Specialist Booking API
 * Specialist appointment booking management for Web-In-Cloud system
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: xdrga@stuba.sk
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  Appointment,
  TimeSlot,
} from '../models';
import {
    AppointmentFromJSON,
    AppointmentToJSON,
    TimeSlotFromJSON,
    TimeSlotToJSON,
} from '../models';

export interface GetAppointmentsRequest {
    clinicId: string;
}

export interface GetTimeSlotsRequest {
    clinicId: string;
}

/**
 * SpecialistBookingApi - interface
 * 
 * @export
 * @interface SpecialistBookingApiInterface
 */
export interface SpecialistBookingApiInterface {
    /**
     * By using clinicId you get list of appointments for a specialist clinic
     * @summary Provides appointments for selected clinic
     * @param {string} clinicId pass the id of the specialist clinic
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SpecialistBookingApiInterface
     */
    getAppointmentsRaw(requestParameters: GetAppointmentsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<Appointment>>>;

    /**
     * By using clinicId you get list of appointments for a specialist clinic
     * Provides appointments for selected clinic
     */
    getAppointments(requestParameters: GetAppointmentsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<Appointment>>;

    /**
     * By using clinicId you get list of configured time slots
     * @summary Provides available time slots for selected clinic
     * @param {string} clinicId pass the id of the specialist clinic
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SpecialistBookingApiInterface
     */
    getTimeSlotsRaw(requestParameters: GetTimeSlotsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<TimeSlot>>>;

    /**
     * By using clinicId you get list of configured time slots
     * Provides available time slots for selected clinic
     */
    getTimeSlots(requestParameters: GetTimeSlotsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<TimeSlot>>;

}

/**
 * 
 */
export class SpecialistBookingApi extends runtime.BaseAPI implements SpecialistBookingApiInterface {

    /**
     * By using clinicId you get list of appointments for a specialist clinic
     * Provides appointments for selected clinic
     */
    async getAppointmentsRaw(requestParameters: GetAppointmentsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<Appointment>>> {
        if (requestParameters.clinicId === null || requestParameters.clinicId === undefined) {
            throw new runtime.RequiredError('clinicId','Required parameter requestParameters.clinicId was null or undefined when calling getAppointments.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/specialist-booking/{clinicId}/appointments`.replace(`{${"clinicId"}}`, encodeURIComponent(String(requestParameters.clinicId))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(AppointmentFromJSON));
    }

    /**
     * By using clinicId you get list of appointments for a specialist clinic
     * Provides appointments for selected clinic
     */
    async getAppointments(requestParameters: GetAppointmentsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<Appointment>> {
        const response = await this.getAppointmentsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * By using clinicId you get list of configured time slots
     * Provides available time slots for selected clinic
     */
    async getTimeSlotsRaw(requestParameters: GetTimeSlotsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<TimeSlot>>> {
        if (requestParameters.clinicId === null || requestParameters.clinicId === undefined) {
            throw new runtime.RequiredError('clinicId','Required parameter requestParameters.clinicId was null or undefined when calling getTimeSlots.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/specialist-booking/{clinicId}/time-slots`.replace(`{${"clinicId"}}`, encodeURIComponent(String(requestParameters.clinicId))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(TimeSlotFromJSON));
    }

    /**
     * By using clinicId you get list of configured time slots
     * Provides available time slots for selected clinic
     */
    async getTimeSlots(requestParameters: GetTimeSlotsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<TimeSlot>> {
        const response = await this.getTimeSlotsRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
