/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { TimeSlot } from "./api/specialist-booking";
export { TimeSlot } from "./api/specialist-booking";
export namespace Components {
    interface SpecialistBookingApp {
        "apiBase": string;
        /**
          * @default ''
         */
        "basePath": string;
        "clinicId": string;
    }
    interface SpecialistBookingAppointmentEditor {
        "apiBase": string;
        "appointmentId": string;
        "clinicId": string;
        /**
          * @default null
         */
        "prefillSlot": TimeSlot | null;
        /**
          * @default 'patient'
         */
        "role": 'patient' | 'doctor';
    }
    interface SpecialistBookingAppointmentList {
        "apiBase": string;
        "clinicId": string;
        /**
          * @default 'patient'
         */
        "role": 'patient' | 'doctor';
    }
    interface SpecialistBookingSlotCalendar {
        "apiBase": string;
        "clinicId": string;
    }
    interface SpecialistBookingSlotEditor {
        "apiBase": string;
        "clinicId": string;
        "slotId": string;
    }
    interface SpecialistBookingWaitlistPanel {
        "apiBase": string;
        "clinicId": string;
    }
}
export interface SpecialistBookingAppointmentEditorCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLSpecialistBookingAppointmentEditorElement;
}
export interface SpecialistBookingAppointmentListCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLSpecialistBookingAppointmentListElement;
}
export interface SpecialistBookingSlotCalendarCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLSpecialistBookingSlotCalendarElement;
}
export interface SpecialistBookingSlotEditorCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLSpecialistBookingSlotEditorElement;
}
export interface SpecialistBookingWaitlistPanelCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLSpecialistBookingWaitlistPanelElement;
}
declare global {
    interface HTMLSpecialistBookingAppElement extends Components.SpecialistBookingApp, HTMLStencilElement {
    }
    var HTMLSpecialistBookingAppElement: {
        prototype: HTMLSpecialistBookingAppElement;
        new (): HTMLSpecialistBookingAppElement;
    };
    interface HTMLSpecialistBookingAppointmentEditorElementEventMap {
        "editor-closed": string;
    }
    interface HTMLSpecialistBookingAppointmentEditorElement extends Components.SpecialistBookingAppointmentEditor, HTMLStencilElement {
        addEventListener<K extends keyof HTMLSpecialistBookingAppointmentEditorElementEventMap>(type: K, listener: (this: HTMLSpecialistBookingAppointmentEditorElement, ev: SpecialistBookingAppointmentEditorCustomEvent<HTMLSpecialistBookingAppointmentEditorElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLSpecialistBookingAppointmentEditorElementEventMap>(type: K, listener: (this: HTMLSpecialistBookingAppointmentEditorElement, ev: SpecialistBookingAppointmentEditorCustomEvent<HTMLSpecialistBookingAppointmentEditorElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLSpecialistBookingAppointmentEditorElement: {
        prototype: HTMLSpecialistBookingAppointmentEditorElement;
        new (): HTMLSpecialistBookingAppointmentEditorElement;
    };
    interface HTMLSpecialistBookingAppointmentListElementEventMap {
        "entry-clicked": string;
        "slots-opened": string;
        "slot-booking-requested": TimeSlot;
        "waitlist-opened": string;
    }
    interface HTMLSpecialistBookingAppointmentListElement extends Components.SpecialistBookingAppointmentList, HTMLStencilElement {
        addEventListener<K extends keyof HTMLSpecialistBookingAppointmentListElementEventMap>(type: K, listener: (this: HTMLSpecialistBookingAppointmentListElement, ev: SpecialistBookingAppointmentListCustomEvent<HTMLSpecialistBookingAppointmentListElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLSpecialistBookingAppointmentListElementEventMap>(type: K, listener: (this: HTMLSpecialistBookingAppointmentListElement, ev: SpecialistBookingAppointmentListCustomEvent<HTMLSpecialistBookingAppointmentListElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLSpecialistBookingAppointmentListElement: {
        prototype: HTMLSpecialistBookingAppointmentListElement;
        new (): HTMLSpecialistBookingAppointmentListElement;
    };
    interface HTMLSpecialistBookingSlotCalendarElementEventMap {
        "slot-clicked": string;
        "slot-create-clicked": string;
        "appointments-opened": string;
    }
    interface HTMLSpecialistBookingSlotCalendarElement extends Components.SpecialistBookingSlotCalendar, HTMLStencilElement {
        addEventListener<K extends keyof HTMLSpecialistBookingSlotCalendarElementEventMap>(type: K, listener: (this: HTMLSpecialistBookingSlotCalendarElement, ev: SpecialistBookingSlotCalendarCustomEvent<HTMLSpecialistBookingSlotCalendarElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLSpecialistBookingSlotCalendarElementEventMap>(type: K, listener: (this: HTMLSpecialistBookingSlotCalendarElement, ev: SpecialistBookingSlotCalendarCustomEvent<HTMLSpecialistBookingSlotCalendarElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLSpecialistBookingSlotCalendarElement: {
        prototype: HTMLSpecialistBookingSlotCalendarElement;
        new (): HTMLSpecialistBookingSlotCalendarElement;
    };
    interface HTMLSpecialistBookingSlotEditorElementEventMap {
        "editor-closed": string;
    }
    interface HTMLSpecialistBookingSlotEditorElement extends Components.SpecialistBookingSlotEditor, HTMLStencilElement {
        addEventListener<K extends keyof HTMLSpecialistBookingSlotEditorElementEventMap>(type: K, listener: (this: HTMLSpecialistBookingSlotEditorElement, ev: SpecialistBookingSlotEditorCustomEvent<HTMLSpecialistBookingSlotEditorElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLSpecialistBookingSlotEditorElementEventMap>(type: K, listener: (this: HTMLSpecialistBookingSlotEditorElement, ev: SpecialistBookingSlotEditorCustomEvent<HTMLSpecialistBookingSlotEditorElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLSpecialistBookingSlotEditorElement: {
        prototype: HTMLSpecialistBookingSlotEditorElement;
        new (): HTMLSpecialistBookingSlotEditorElement;
    };
    interface HTMLSpecialistBookingWaitlistPanelElementEventMap {
        "appointments-opened": string;
    }
    interface HTMLSpecialistBookingWaitlistPanelElement extends Components.SpecialistBookingWaitlistPanel, HTMLStencilElement {
        addEventListener<K extends keyof HTMLSpecialistBookingWaitlistPanelElementEventMap>(type: K, listener: (this: HTMLSpecialistBookingWaitlistPanelElement, ev: SpecialistBookingWaitlistPanelCustomEvent<HTMLSpecialistBookingWaitlistPanelElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLSpecialistBookingWaitlistPanelElementEventMap>(type: K, listener: (this: HTMLSpecialistBookingWaitlistPanelElement, ev: SpecialistBookingWaitlistPanelCustomEvent<HTMLSpecialistBookingWaitlistPanelElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLSpecialistBookingWaitlistPanelElement: {
        prototype: HTMLSpecialistBookingWaitlistPanelElement;
        new (): HTMLSpecialistBookingWaitlistPanelElement;
    };
    interface HTMLElementTagNameMap {
        "specialist-booking-app": HTMLSpecialistBookingAppElement;
        "specialist-booking-appointment-editor": HTMLSpecialistBookingAppointmentEditorElement;
        "specialist-booking-appointment-list": HTMLSpecialistBookingAppointmentListElement;
        "specialist-booking-slot-calendar": HTMLSpecialistBookingSlotCalendarElement;
        "specialist-booking-slot-editor": HTMLSpecialistBookingSlotEditorElement;
        "specialist-booking-waitlist-panel": HTMLSpecialistBookingWaitlistPanelElement;
    }
}
declare namespace LocalJSX {
    interface SpecialistBookingApp {
        "apiBase"?: string;
        /**
          * @default ''
         */
        "basePath"?: string;
        "clinicId"?: string;
    }
    interface SpecialistBookingAppointmentEditor {
        "apiBase"?: string;
        "appointmentId"?: string;
        "clinicId"?: string;
        "onEditor-closed"?: (event: SpecialistBookingAppointmentEditorCustomEvent<string>) => void;
        /**
          * @default null
         */
        "prefillSlot"?: TimeSlot | null;
        /**
          * @default 'patient'
         */
        "role"?: 'patient' | 'doctor';
    }
    interface SpecialistBookingAppointmentList {
        "apiBase"?: string;
        "clinicId"?: string;
        "onEntry-clicked"?: (event: SpecialistBookingAppointmentListCustomEvent<string>) => void;
        "onSlot-booking-requested"?: (event: SpecialistBookingAppointmentListCustomEvent<TimeSlot>) => void;
        "onSlots-opened"?: (event: SpecialistBookingAppointmentListCustomEvent<string>) => void;
        "onWaitlist-opened"?: (event: SpecialistBookingAppointmentListCustomEvent<string>) => void;
        /**
          * @default 'patient'
         */
        "role"?: 'patient' | 'doctor';
    }
    interface SpecialistBookingSlotCalendar {
        "apiBase"?: string;
        "clinicId"?: string;
        "onAppointments-opened"?: (event: SpecialistBookingSlotCalendarCustomEvent<string>) => void;
        "onSlot-clicked"?: (event: SpecialistBookingSlotCalendarCustomEvent<string>) => void;
        "onSlot-create-clicked"?: (event: SpecialistBookingSlotCalendarCustomEvent<string>) => void;
    }
    interface SpecialistBookingSlotEditor {
        "apiBase"?: string;
        "clinicId"?: string;
        "onEditor-closed"?: (event: SpecialistBookingSlotEditorCustomEvent<string>) => void;
        "slotId"?: string;
    }
    interface SpecialistBookingWaitlistPanel {
        "apiBase"?: string;
        "clinicId"?: string;
        "onAppointments-opened"?: (event: SpecialistBookingWaitlistPanelCustomEvent<string>) => void;
    }

    interface SpecialistBookingAppAttributes {
        "basePath": string;
        "apiBase": string;
        "clinicId": string;
    }
    interface SpecialistBookingAppointmentEditorAttributes {
        "appointmentId": string;
        "apiBase": string;
        "clinicId": string;
        "role": 'patient' | 'doctor';
    }
    interface SpecialistBookingAppointmentListAttributes {
        "apiBase": string;
        "clinicId": string;
        "role": 'patient' | 'doctor';
    }
    interface SpecialistBookingSlotCalendarAttributes {
        "apiBase": string;
        "clinicId": string;
    }
    interface SpecialistBookingSlotEditorAttributes {
        "slotId": string;
        "apiBase": string;
        "clinicId": string;
    }
    interface SpecialistBookingWaitlistPanelAttributes {
        "apiBase": string;
        "clinicId": string;
    }

    interface IntrinsicElements {
        "specialist-booking-app": Omit<SpecialistBookingApp, keyof SpecialistBookingAppAttributes> & { [K in keyof SpecialistBookingApp & keyof SpecialistBookingAppAttributes]?: SpecialistBookingApp[K] } & { [K in keyof SpecialistBookingApp & keyof SpecialistBookingAppAttributes as `attr:${K}`]?: SpecialistBookingAppAttributes[K] } & { [K in keyof SpecialistBookingApp & keyof SpecialistBookingAppAttributes as `prop:${K}`]?: SpecialistBookingApp[K] };
        "specialist-booking-appointment-editor": Omit<SpecialistBookingAppointmentEditor, keyof SpecialistBookingAppointmentEditorAttributes> & { [K in keyof SpecialistBookingAppointmentEditor & keyof SpecialistBookingAppointmentEditorAttributes]?: SpecialistBookingAppointmentEditor[K] } & { [K in keyof SpecialistBookingAppointmentEditor & keyof SpecialistBookingAppointmentEditorAttributes as `attr:${K}`]?: SpecialistBookingAppointmentEditorAttributes[K] } & { [K in keyof SpecialistBookingAppointmentEditor & keyof SpecialistBookingAppointmentEditorAttributes as `prop:${K}`]?: SpecialistBookingAppointmentEditor[K] };
        "specialist-booking-appointment-list": Omit<SpecialistBookingAppointmentList, keyof SpecialistBookingAppointmentListAttributes> & { [K in keyof SpecialistBookingAppointmentList & keyof SpecialistBookingAppointmentListAttributes]?: SpecialistBookingAppointmentList[K] } & { [K in keyof SpecialistBookingAppointmentList & keyof SpecialistBookingAppointmentListAttributes as `attr:${K}`]?: SpecialistBookingAppointmentListAttributes[K] } & { [K in keyof SpecialistBookingAppointmentList & keyof SpecialistBookingAppointmentListAttributes as `prop:${K}`]?: SpecialistBookingAppointmentList[K] };
        "specialist-booking-slot-calendar": Omit<SpecialistBookingSlotCalendar, keyof SpecialistBookingSlotCalendarAttributes> & { [K in keyof SpecialistBookingSlotCalendar & keyof SpecialistBookingSlotCalendarAttributes]?: SpecialistBookingSlotCalendar[K] } & { [K in keyof SpecialistBookingSlotCalendar & keyof SpecialistBookingSlotCalendarAttributes as `attr:${K}`]?: SpecialistBookingSlotCalendarAttributes[K] } & { [K in keyof SpecialistBookingSlotCalendar & keyof SpecialistBookingSlotCalendarAttributes as `prop:${K}`]?: SpecialistBookingSlotCalendar[K] };
        "specialist-booking-slot-editor": Omit<SpecialistBookingSlotEditor, keyof SpecialistBookingSlotEditorAttributes> & { [K in keyof SpecialistBookingSlotEditor & keyof SpecialistBookingSlotEditorAttributes]?: SpecialistBookingSlotEditor[K] } & { [K in keyof SpecialistBookingSlotEditor & keyof SpecialistBookingSlotEditorAttributes as `attr:${K}`]?: SpecialistBookingSlotEditorAttributes[K] } & { [K in keyof SpecialistBookingSlotEditor & keyof SpecialistBookingSlotEditorAttributes as `prop:${K}`]?: SpecialistBookingSlotEditor[K] };
        "specialist-booking-waitlist-panel": Omit<SpecialistBookingWaitlistPanel, keyof SpecialistBookingWaitlistPanelAttributes> & { [K in keyof SpecialistBookingWaitlistPanel & keyof SpecialistBookingWaitlistPanelAttributes]?: SpecialistBookingWaitlistPanel[K] } & { [K in keyof SpecialistBookingWaitlistPanel & keyof SpecialistBookingWaitlistPanelAttributes as `attr:${K}`]?: SpecialistBookingWaitlistPanelAttributes[K] } & { [K in keyof SpecialistBookingWaitlistPanel & keyof SpecialistBookingWaitlistPanelAttributes as `prop:${K}`]?: SpecialistBookingWaitlistPanel[K] };
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "specialist-booking-app": LocalJSX.IntrinsicElements["specialist-booking-app"] & JSXBase.HTMLAttributes<HTMLSpecialistBookingAppElement>;
            "specialist-booking-appointment-editor": LocalJSX.IntrinsicElements["specialist-booking-appointment-editor"] & JSXBase.HTMLAttributes<HTMLSpecialistBookingAppointmentEditorElement>;
            "specialist-booking-appointment-list": LocalJSX.IntrinsicElements["specialist-booking-appointment-list"] & JSXBase.HTMLAttributes<HTMLSpecialistBookingAppointmentListElement>;
            "specialist-booking-slot-calendar": LocalJSX.IntrinsicElements["specialist-booking-slot-calendar"] & JSXBase.HTMLAttributes<HTMLSpecialistBookingSlotCalendarElement>;
            "specialist-booking-slot-editor": LocalJSX.IntrinsicElements["specialist-booking-slot-editor"] & JSXBase.HTMLAttributes<HTMLSpecialistBookingSlotEditorElement>;
            "specialist-booking-waitlist-panel": LocalJSX.IntrinsicElements["specialist-booking-waitlist-panel"] & JSXBase.HTMLAttributes<HTMLSpecialistBookingWaitlistPanelElement>;
        }
    }
}
