/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface SpecialistBookingOverview {
    }
}
declare global {
    interface HTMLSpecialistBookingOverviewElement extends Components.SpecialistBookingOverview, HTMLStencilElement {
    }
    var HTMLSpecialistBookingOverviewElement: {
        prototype: HTMLSpecialistBookingOverviewElement;
        new (): HTMLSpecialistBookingOverviewElement;
    };
    interface HTMLElementTagNameMap {
        "specialist-booking-overview": HTMLSpecialistBookingOverviewElement;
    }
}
declare namespace LocalJSX {
    interface SpecialistBookingOverview {
    }
    interface IntrinsicElements {
        "specialist-booking-overview": SpecialistBookingOverview;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "specialist-booking-overview": LocalJSX.IntrinsicElements["specialist-booking-overview"] & JSXBase.HTMLAttributes<HTMLSpecialistBookingOverviewElement>;
        }
    }
}
